export { HeroSection } from "./hero-section";
export { AboutSection } from "./about-section";
export { WhyUsSection } from "./why-us-section";
export { ServicesSection } from "./services-section";
export { DemosSection } from "./demos-section";
export { SemillaSection } from "./semilla-section";
export { PartnershipsSection } from "./partnerships-section";
export { ProjectsSection } from "./projects-section";
export { StoriesSection } from "./stories-section";
